import { Component } from '@angular/core';
import { NoteService } from '../../services/note.service';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Note } from '../../models/note.interface';

@Component({
  selector: 'app-note-create',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './note-create.component.html',
  styleUrls: ['./note-create.component.scss'],
})
export class NoteCreateComponent {
  note = {
    id: '',
    title: '',
    content: '',
    tags: [] as string[],
    isArchived: false,
    createdAt: new Date(),
    lastEdited: new Date(),
  };

  constructor(private noteService: NoteService, private router: Router) {}

  addTagsFromInput(tagsString: string) {
    if (!tagsString.trim()) return;

    const tagsArray = tagsString
      .split(',')
      .map((tag) => tag.trim())
      .filter((tag) => tag.length > 0 && !this.note.tags.includes(tag));

    this.note.tags = [...this.note.tags, ...tagsArray];
    this.onContentChange();
  }

  removeTag(index: number) {
    this.note.tags.splice(index, 1);
    this.onContentChange();
  }

  onContentChange() {
    this.note.lastEdited = new Date();
  }

  getLastEditedText(): string {
    if (
      !this.note.title.trim() &&
      !this.note.content.trim() &&
      this.note.tags.length === 0
    ) {
      return 'Not yet saved';
    }

    const now = new Date();
    const diffTime = Math.abs(now.getTime() - this.note.lastEdited.getTime());
    const diffMinutes = Math.floor(diffTime / (1000 * 60));

    if (diffMinutes < 1) return 'Just now';
    if (diffMinutes < 60)
      return `${diffMinutes} minute${diffMinutes > 1 ? 's' : ''} ago`;

    const diffHours = Math.floor(diffMinutes / 60);
    if (diffHours < 24)
      return `${diffHours} hour${diffHours > 1 ? 's' : ''} ago`;

    const diffDays = Math.floor(diffHours / 24);
    return `${diffDays} day${diffDays > 1 ? 's' : ''} ago`;
  }

  saveNote() {
    if (!this.note.title.trim()) {
      alert('Please enter a title for your note.');
      return;
    }

    const noteToSave: Note = {
      id: '', // This will be generated by the service
      title: this.note.title.trim(),
      content: this.note.content.trim(),
      tags: this.note.tags,
      createdAt: new Date(),
      lastEdited: new Date(),
      isArchived: false,
    };

    const savedNote = this.noteService.createNote(noteToSave);

    // Navigate to the newly created note
    this.router.navigate(['/dashboard/notes', savedNote.id]);
  }

  cancelCreation() {
    const hasContent =
      this.note.title.trim() ||
      this.note.content.trim() ||
      this.note.tags.length > 0;

    if (hasContent) {
      if (
        confirm('Are you sure you want to cancel? Your changes will be lost.')
      ) {
        this.router.navigate(['/dashboard/notes']);
      }
    } else {
      this.router.navigate(['/dashboard/notes']);
    }
  }
}
